require'nvim-treesitter.configs'.setup {
  -- One of "all", "maintained" (parsers with maintainers), or a list of languages
  ensure_installed = "maintained",

  -- Install languages synchronously (only applied to `ensure_installed`)
  sync_install = false,

  -- List of parsers to ignore installing
  ignore_install = {
--      "bash",
      "beancount",
      "bibtex",
--      "c",
      "c_sharp",
      "clojure",
      "cmake",
      "comment",
      "commonlisp",
--      "cpp",
      "css",
      "cuda",
      "d",
--      "dart",
      "devicetree",
      "dockerfile",
      "dot",
      "eex",
      "elixir",
      "elm",
      "erlang",
      "fennel",
      "fish",
      "foam",
      "fortran",
      "fusion",
      "Godot (gdscript)",
      "Glimmer and Ember",
      "glsl",
      "go",
      "Godot Resources (gdresource)",
      "gomod",
      "gowork",
      "graphql",
      "hack",
      "haskell",
      "hcl",
      "heex",
      "hjson",
      "hocon",
      "html",
      "http",
      "java",
      "javascript",
      "jsdoc",
      "json",
      "json5",
      "JSON with comments",
      "julia",
      "kotlin",
--      "latex",
      "ledger",
      "llvm",
      "lua",
      "make",
      "markdown",
      "ninja",
      "nix",
      "norg",
      "ocaml",
      "ocaml_interface",
      "ocamllex",
      "pascal",
      "perl",
      "php",
      "phpdoc",
      "pioasm",
      "prisma",
      "pug",
--      "python",
      "ql",
--      "Tree-sitter query language",
      "r",
      "rasi",
      "regex",
      "rst",
      "ruby",
      "rust",
      "scala",
      "scss",
      "sparql",
      "supercollider",
      "surface",
      "svelte",
      "swift",
      "teal",
      "tlaplus",
      "toml",
      "tsx",
      "turtle",
      "typescript",
      "vala",
      "verilog",
      "vim",
      "vue",
      "yaml",
      "yang",
      "zig"
  },

  highlight = {
    -- `false` will disable the whole extension
    enable = true,

    -- list of language that will be disabled
    disable = {
--      "bash",
      "beancount",
      "bibtex",
--      "c",
      "c_sharp",
      "clojure",
      "cmake",
      "comment",
      "commonlisp",
--      "cpp",
      "css",
      "cuda",
      "d",
--      "dart",
      "devicetree",
      "dockerfile",
      "dot",
      "eex",
      "elixir",
      "elm",
      "erlang",
      "fennel",
      "fish",
      "foam",
      "fortran",
      "fusion",
      "Godot (gdscript)",
      "Glimmer and Ember",
      "glsl",
      "go",
      "Godot Resources (gdresource)",
      "gomod",
      "gowork",
      "graphql",
      "hack",
      "haskell",
      "hcl",
      "heex",
      "hjson",
      "hocon",
      "html",
      "http",
      "java",
      "javascript",
      "jsdoc",
      "json",
      "json5",
      "JSON with comments",
      "julia",
      "kotlin",
--      "latex",
      "ledger",
      "llvm",
      "lua",
      "make",
      "markdown",
      "ninja",
      "nix",
      "norg",
      "ocaml",
      "ocaml_interface",
      "ocamllex",
      "pascal",
      "perl",
      "php",
      "phpdoc",
      "pioasm",
      "prisma",
      "pug",
--      "python",
      "ql",
--      "Tree-sitter query language",
      "r",
      "rasi",
      "regex",
      "rst",
      "ruby",
      "rust",
      "scala",
      "scss",
      "sparql",
      "supercollider",
      "surface",
      "svelte",
      "swift",
      "teal",
      "tlaplus",
      "toml",
      "tsx",
      "turtle",
      "typescript",
      "vala",
      "verilog",
      "vim",
      "vue",
      "yaml",
      "yang",
      "zig"
    },

      -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
      -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
      -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
  },
}
